<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite errors="0" failures="1" hostname="lucydeMacBook-Pro.local" name="pytest" skipped="0" tests="2" time="0.045" timestamp="2019-09-11T16:33:55.533128"><testcase classname="test.TestClass" file="test.py" line="4" name="test_one" time="0.001"></testcase><testcase classname="test.TestClass" file="test.py" line="8" name="test_two" time="0.001"><failure message="AssertionError: assert False
 +  where False = hasattr(&apos;hello&apos;, &apos;check&apos;)">self = &lt;test.TestClass object at 0x10e414e10&gt;

    def test_two(self):
        x = &quot;hello&quot;
&gt;       assert hasattr(x, &apos;check&apos;)
E       AssertionError: assert False
E        +  where False = hasattr(&apos;hello&apos;, &apos;check&apos;)

test.py:11: AssertionError</failure></testcase></testsuite></testsuites>